Config:
  checkerTime: 10 #in ticks;
  debug-mode: false
  lore-format:
    - "{item-lore}"
    - ""
    - "&7Rarity: {rarity-prefix}"
  enable-glow: true
  inventory-blacklist:
    types:
      - "MERCHANT" #types of inventories to exclude from rarity to be applied https://jd.papermc.io/paper/1.21.1/org/bukkit/event/inventory/InventoryType.html
      - "WORKBENCH"
    titles:
      - "Example inventory title" #<- Inventory title to exclude from rarity to be applied